import assert from "node:assert/strict";
import test from "node:test";
import {
  editableQuizItems,
  isAutogeneratedSatQuiz,
  isQuizRepositoryItem,
  quizRepositoryItems,
  quizRepositoryLabel,
} from "./quiz-repository.ts";

const reusable = {
  id: "quiz-bank",
  courseId: "course-1",
  sessionId: null,
  title: "Xavier custom bank quiz",
  status: "published",
  deliveryPhase: "before_session",
  questionCount: 4,
  instructions: "Reusable quiz assembled from official SAT/PSAT bank questions.",
};

const autogen = {
  id: "quiz-autogen",
  courseId: "course-1",
  sessionId: "session-1",
  sessionTitle: "Michelle’s SAT Session with Xavier",
  title: "SAT pre-work (30–50 questions) — Michelle’s SAT Session with Xavier",
  status: "published",
  deliveryPhase: "before_session",
  questionCount: 36,
  instructions: "30–50 official-bank questions for this session (not a full-length SAT).",
};

test("quiz repository includes reusable tutor-built quizzes and autogenerated session copies", () => {
  assert.equal(isQuizRepositoryItem(reusable), true);
  assert.equal(isAutogeneratedSatQuiz(autogen), true);
  assert.equal(isQuizRepositoryItem(autogen), true);
  assert.equal(
    isQuizRepositoryItem({
      ...autogen,
      id: "other-hw",
      title: "Evidence mini-section",
      instructions: "Complete before the meeting.",
    }),
    true,
  );
  assert.equal(
    isQuizRepositoryItem({
      ...autogen,
      id: "during",
      deliveryPhase: "during_session",
      title: "In-session practice",
    }),
    false,
  );
  assert.deepEqual(
    quizRepositoryItems([autogen, reusable, { ...reusable, id: "archived", status: "archived" }]).map(
      (item) => item.id,
    ),
    ["quiz-bank", "quiz-autogen"],
  );
  assert.match(quizRepositoryLabel(autogen), /Michelle/);
  assert.match(quizRepositoryLabel(reusable), /reusable/);
});

test("editable quiz list includes reusable bank quizzes and session pre-work copies", () => {
  const during = {
    ...autogen,
    id: "during",
    deliveryPhase: "during_session",
    title: "In-session practice",
  };
  const assignedCopy = {
    ...autogen,
    id: "quiz-clone",
    title: "Evidence mini-section (assigned)",
    instructions: "Complete before the meeting.",
  };
  assert.deepEqual(
    editableQuizItems([during, assignedCopy, reusable, { ...reusable, id: "archived", status: "archived" }]).map(
      (item) => item.id,
    ),
    ["quiz-bank", "quiz-clone"],
  );
});
