import {
  isReusableBankQuiz,
  type BankQuizCandidate,
} from "./assignable-bank-quizzes.ts";

export type QuizRepositoryItem = BankQuizCandidate & {
  instructions?: string | null;
  sessionTitle?: string | null;
};

export function isAutogeneratedSatQuiz(
  item: Pick<QuizRepositoryItem, "title" | "instructions">,
): boolean {
  const title = item.title.trim().toLowerCase();
  const instructions = (item.instructions ?? "").toLowerCase();
  return (
    title.includes("sat pre-work (30–50 questions)") ||
    title.includes("sat pre-work (30-50 questions)") ||
    title.includes("full-length sat diagnostic") ||
    instructions.includes("30–50 official-bank questions for this session") ||
    instructions.includes("complete this full-length college board sat practice test")
  );
}

export function isQuizRepositoryItem(item: QuizRepositoryItem): boolean {
  if (item.status === "archived") return false;
  if (item.deliveryPhase !== "before_session") return false;
  if (isReusableBankQuiz(item)) return true;
  return Boolean(item.sessionId) && isAutogeneratedSatQuiz(item);
}

export function quizRepositoryItems<T extends QuizRepositoryItem>(items: T[]): T[] {
  const seen = new Set<string>();
  const result: T[] = [];
  for (const item of items) {
    if (seen.has(item.id) || !isQuizRepositoryItem(item)) continue;
    seen.add(item.id);
    result.push(item);
  }
  return result.sort((left, right) => {
    const leftReusable = left.sessionId == null ? 0 : 1;
    const rightReusable = right.sessionId == null ? 0 : 1;
    if (leftReusable !== rightReusable) return leftReusable - rightReusable;
    return left.title.localeCompare(right.title);
  });
}

export function quizRepositoryLabel(
  item: Pick<QuizRepositoryItem, "title" | "questionCount" | "sessionId" | "sessionTitle">,
): string {
  const source = item.sessionId
    ? item.sessionTitle?.trim() || "session copy"
    : "reusable";
  return `${item.title} · ${item.questionCount} questions · ${source}`;
}
