import assert from "node:assert/strict";
import test from "node:test";
import { planAutogeneratedSatPrework, homeworkKindForSatPreworkReset } from "./autogenerated-sat-prework-plan.ts";

test("SAT bookings get routine 30–50 MCQ prework unless the Taito Oct-2 diagnostic applies", () => {
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "SAT",
      existingLiveQuestionCount: 0,
      isTaitoFirstSat: false,
      isXavierCapability: false,
    }),
    { action: "assign", homeworkKind: "routine" },
  );
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "SAT Reading",
      existingLiveQuestionCount: 0,
      isTaitoFirstSat: true,
      isXavierCapability: false,
    }),
    { action: "assign", homeworkKind: "diagnostic" },
  );
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "SAT",
      existingLiveQuestionCount: 0,
      isTaitoFirstSat: true,
      isXavierCapability: true,
    }),
    { action: "assign", homeworkKind: "routine" },
  );
});

test("autogen is idempotent when live prework already exists and skips non-SAT sessions", () => {
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "SAT",
      existingLiveQuestionCount: 36,
      isTaitoFirstSat: false,
      isXavierCapability: false,
    }),
    { action: "skip", reason: "already-assigned" },
  );
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "SAT",
      existingLiveQuestionCount: 0,
      hasLiveHomework: true,
      isTaitoFirstSat: false,
      isXavierCapability: false,
    }),
    { action: "skip", reason: "already-assigned" },
  );
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "IELTS",
      existingLiveQuestionCount: 0,
      isTaitoFirstSat: false,
      isXavierCapability: false,
    }),
    { action: "skip", reason: "not-sat" },
  );
});

test("session reset uses diagnostic only for Taito Oct 2 and routine for later SAT", () => {
  assert.equal(
    homeworkKindForSatPreworkReset({
      subject: "SAT",
      isTaitoFirstSat: true,
      isXavierCapability: false,
    }),
    "diagnostic",
  );
  assert.equal(
    homeworkKindForSatPreworkReset({
      subject: "SAT",
      isTaitoFirstSat: false,
      isXavierCapability: false,
    }),
    "routine",
  );
  assert.equal(
    homeworkKindForSatPreworkReset({
      subject: "SAT",
      isTaitoFirstSat: true,
      isXavierCapability: true,
    }),
    "routine",
  );
  assert.equal(
    homeworkKindForSatPreworkReset({
      subject: "IELTS",
      isTaitoFirstSat: false,
      isXavierCapability: false,
    }),
    null,
  );
});
