import { normalizedSessionSubject } from "./session-schedule.ts";

export type AutogeneratedSatPreworkPlan =
  | { action: "skip"; reason: "not-sat" | "already-assigned" }
  | { action: "assign"; homeworkKind: "routine" | "diagnostic" };

export function planAutogeneratedSatPrework(input: {
  subject: string;
  existingLiveQuestionCount: number;
  isTaitoFirstSat: boolean;
  isXavierCapability: boolean;
}): AutogeneratedSatPreworkPlan {
  if (normalizedSessionSubject(input.subject) !== "SAT") {
    return { action: "skip", reason: "not-sat" };
  }
  if (input.existingLiveQuestionCount > 0) {
    return { action: "skip", reason: "already-assigned" };
  }
  if (input.isTaitoFirstSat && !input.isXavierCapability) {
    return { action: "assign", homeworkKind: "diagnostic" };
  }
  return { action: "assign", homeworkKind: "routine" };
}
