import assert from "node:assert/strict";
import test from "node:test";
import { planAutogeneratedSatPrework } from "./autogenerated-sat-prework-plan.ts";

test("SAT bookings get routine 30–50 MCQ prework unless the Taito Oct-2 diagnostic applies", () => {
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "SAT",
      existingLiveQuestionCount: 0,
      isTaitoFirstSat: false,
      isXavierCapability: false,
    }),
    { action: "assign", homeworkKind: "routine" },
  );
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "SAT Reading",
      existingLiveQuestionCount: 0,
      isTaitoFirstSat: true,
      isXavierCapability: false,
    }),
    { action: "assign", homeworkKind: "diagnostic" },
  );
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "SAT",
      existingLiveQuestionCount: 0,
      isTaitoFirstSat: true,
      isXavierCapability: true,
    }),
    { action: "assign", homeworkKind: "routine" },
  );
});

test("autogen is idempotent when live prework already exists and skips non-SAT sessions", () => {
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "SAT",
      existingLiveQuestionCount: 36,
      isTaitoFirstSat: false,
      isXavierCapability: false,
    }),
    { action: "skip", reason: "already-assigned" },
  );
  assert.deepEqual(
    planAutogeneratedSatPrework({
      subject: "IELTS",
      existingLiveQuestionCount: 0,
      isTaitoFirstSat: false,
      isXavierCapability: false,
    }),
    { action: "skip", reason: "not-sat" },
  );
});
