import { isEnglishSessionSubject } from "./session-schedule.ts";

export type AutogeneratedEnglishPreworkPlan =
  | { action: "skip"; reason: "not-english" | "already-assigned" }
  | { action: "assign"; homeworkKind: "routine" | "diagnostic"; setIndex: number };

/**
 * First Taito English session (Oct 23 with Nika) gets a short diagnostic-style
 * reading set. Later English sessions get shorter routine sets. Non-Taito
 * English sessions get routine unless Cos assigns diagnostic explicitly.
 */
export function planAutogeneratedEnglishPrework(input: {
  subject: string;
  existingLiveQuestionCount: number;
  /** Live before-session row of the planned kind, including empty published copies. */
  hasLiveHomework?: boolean;
  isTaitoFirstEnglish: boolean;
  taitoEnglishIndex?: number;
}): AutogeneratedEnglishPreworkPlan {
  if (!isEnglishSessionSubject(input.subject)) {
    return { action: "skip", reason: "not-english" };
  }
  if (input.hasLiveHomework === true || input.existingLiveQuestionCount > 0) {
    return { action: "skip", reason: "already-assigned" };
  }
  if (input.isTaitoFirstEnglish || input.taitoEnglishIndex === 0) {
    return { action: "assign", homeworkKind: "diagnostic", setIndex: 0 };
  }
  const laterIndex = input.taitoEnglishIndex != null && input.taitoEnglishIndex > 0
    ? input.taitoEnglishIndex
    : 1;
  return { action: "assign", homeworkKind: "routine", setIndex: laterIndex };
}

export function homeworkKindForEnglishPreworkReset(input: {
  subject: string;
  isTaitoFirstEnglish: boolean;
  taitoEnglishIndex?: number;
}): "diagnostic" | "routine" | null {
  const planned = planAutogeneratedEnglishPrework({
    subject: input.subject,
    existingLiveQuestionCount: 0,
    isTaitoFirstEnglish: input.isTaitoFirstEnglish,
    taitoEnglishIndex: input.taitoEnglishIndex,
  });
  return planned.action === "assign" ? planned.homeworkKind : null;
}

export function englishDiagnosticTimeLimitMinutes(questionCount: number): number {
  return Math.min(60, Math.max(30, Math.round(questionCount * 1.75) || 30));
}

export function englishRoutineTimeLimitMinutes(questionCount: number): number {
  return Math.min(45, Math.max(20, Math.round(questionCount * 1.75) || 20));
}
