import { db, sessionsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { assignSessionPreworkFromBank } from "./assign-session-prework.ts";
import { ensureAutogeneratedEnglishPrework } from "./ielts-style-bank.ts";
import { isEnglishSessionSubject, isTaitoFirstSatSession } from "./session-schedule.ts";
import { isXavierSatCapabilitySession } from "./xavier-sat-capability-session.ts";
import { planAutogeneratedSatPrework } from "./autogenerated-sat-prework-plan.ts";
import { shouldSkipAutogeneratedPreworkAssign } from "./session-prework-dedupe.ts";
import {
  listLiveBeforeSessionHomework,
  liveSessionPreworkQuestionCount,
  withSessionPreworkLock,
} from "./session-prework-live.ts";

export { planAutogeneratedSatPrework } from "./autogenerated-sat-prework-plan.ts";
export { liveSessionPreworkQuestionCount } from "./session-prework-live.ts";

export async function ensureAutogeneratedSatPrework(
  sessionId: string,
  actorUserId?: string | null,
): Promise<
  | { skipped: true; reason: string; assignmentId?: string | null }
  | Awaited<ReturnType<typeof assignSessionPreworkFromBank>>
> {
  const [session] = await db
    .select()
    .from(sessionsTable)
    .where(eq(sessionsTable.id, sessionId))
    .limit(1);
  if (!session) {
    return { skipped: true, reason: "session-not-found" };
  }
  if (isEnglishSessionSubject(session.subject)) {
    return ensureAutogeneratedEnglishPrework(session.id, actorUserId);
  }
  return withSessionPreworkLock(session.id, async () => {
    const live = await listLiveBeforeSessionHomework(session.id);
    const existing = await liveSessionPreworkQuestionCount(session.id);
    const planned = planAutogeneratedSatPrework({
      subject: session.subject,
      existingLiveQuestionCount: 0,
      isTaitoFirstSat: isTaitoFirstSatSession(session),
      isXavierCapability: isXavierSatCapabilitySession(session),
    });
    if (planned.action === "skip") {
      return {
        skipped: true as const,
        reason: planned.reason,
        assignmentId: existing.assignmentId,
      };
    }
    const skip = shouldSkipAutogeneratedPreworkAssign({
      plannedKind: planned.homeworkKind,
      liveHomework: live,
    });
    if (skip.skip) {
      return {
        skipped: true as const,
        reason: skip.reason,
        assignmentId: skip.assignmentId,
      };
    }
    try {
      return await assignSessionPreworkFromBank({
        sessionId: session.id,
        actorUserId,
        homeworkKind: planned.homeworkKind,
        skipArchiveExisting: true,
        mcqOnly: planned.homeworkKind === "routine",
      });
    } catch {
      return {
        skipped: true as const,
        reason: "bank-unavailable",
        assignmentId: existing.assignmentId,
      };
    }
  });
}
