import { normalizedSessionSubject } from "./session-schedule.ts";

export type AutogeneratedSatPreworkPlan =
  | { action: "skip"; reason: "not-sat" | "already-assigned" }
  | { action: "assign"; homeworkKind: "routine" | "diagnostic" };

export function planAutogeneratedSatPrework(input: {
  subject: string;
  existingLiveQuestionCount: number;
  isTaitoFirstSat: boolean;
  isXavierCapability: boolean;
}): AutogeneratedSatPreworkPlan {
  if (normalizedSessionSubject(input.subject) !== "SAT") {
    return { action: "skip", reason: "not-sat" };
  }
  if (input.existingLiveQuestionCount > 0) {
    return { action: "skip", reason: "already-assigned" };
  }
  if (input.isTaitoFirstSat && !input.isXavierCapability) {
    return { action: "assign", homeworkKind: "diagnostic" };
  }
  return { action: "assign", homeworkKind: "routine" };
}

/** Rebuild/reset uses the same diagnostic-vs-routine rule as first assign. */
export function homeworkKindForSatPreworkReset(input: {
  subject: string;
  isTaitoFirstSat: boolean;
  isXavierCapability: boolean;
}): "diagnostic" | "routine" | null {
  const planned = planAutogeneratedSatPrework({
    subject: input.subject,
    existingLiveQuestionCount: 0,
    isTaitoFirstSat: input.isTaitoFirstSat,
    isXavierCapability: input.isXavierCapability,
  });
  return planned.action === "assign" ? planned.homeworkKind : null;
}
