import assert from "node:assert/strict";
import test from "node:test";
import {
  englishDiagnosticTimeLimitMinutes,
  englishRoutineTimeLimitMinutes,
  homeworkKindForEnglishPreworkReset,
  planAutogeneratedEnglishPrework,
} from "./autogenerated-english-prework-plan.ts";

test("first Taito English session gets a short diagnostic; later English gets routine", () => {
  assert.deepEqual(
    planAutogeneratedEnglishPrework({
      subject: "IELTS",
      existingLiveQuestionCount: 0,
      isTaitoFirstEnglish: true,
      taitoEnglishIndex: 0,
    }),
    { action: "assign", homeworkKind: "diagnostic", setIndex: 0 },
  );
  assert.deepEqual(
    planAutogeneratedEnglishPrework({
      subject: "English",
      existingLiveQuestionCount: 0,
      isTaitoFirstEnglish: false,
      taitoEnglishIndex: 1,
    }),
    { action: "assign", homeworkKind: "routine", setIndex: 1 },
  );
  assert.deepEqual(
    planAutogeneratedEnglishPrework({
      subject: "IELTS",
      existingLiveQuestionCount: 0,
      isTaitoFirstEnglish: false,
      taitoEnglishIndex: 2,
    }),
    { action: "assign", homeworkKind: "routine", setIndex: 2 },
  );
});

test("English autogen is idempotent and skips SAT sessions", () => {
  assert.deepEqual(
    planAutogeneratedEnglishPrework({
      subject: "IELTS",
      existingLiveQuestionCount: 18,
      isTaitoFirstEnglish: true,
    }),
    { action: "skip", reason: "already-assigned" },
  );
  assert.deepEqual(
    planAutogeneratedEnglishPrework({
      subject: "SAT",
      existingLiveQuestionCount: 0,
      isTaitoFirstEnglish: false,
    }),
    { action: "skip", reason: "not-english" },
  );
});

test("English reset uses diagnostic only for the first Taito English session", () => {
  assert.equal(
    homeworkKindForEnglishPreworkReset({
      subject: "IELTS",
      isTaitoFirstEnglish: true,
      taitoEnglishIndex: 0,
    }),
    "diagnostic",
  );
  assert.equal(
    homeworkKindForEnglishPreworkReset({
      subject: "English conversation",
      isTaitoFirstEnglish: false,
      taitoEnglishIndex: 1,
    }),
    "routine",
  );
  assert.equal(
    homeworkKindForEnglishPreworkReset({
      subject: "SAT",
      isTaitoFirstEnglish: false,
    }),
    null,
  );
});

test("English time limits stay shorter than SAT full-length floors", () => {
  assert.equal(englishDiagnosticTimeLimitMinutes(24), 42);
  assert.equal(englishRoutineTimeLimitMinutes(12), 21);
  assert.ok(englishDiagnosticTimeLimitMinutes(24) < 134);
});
