import { and, eq, sql } from "drizzle-orm";
import {
  assignmentQuestionsTable,
  assignmentsTable,
  db,
  sessionsTable,
} from "@workspace/db";
import { assignPreworkFromBank } from "./sat-bank-service.ts";
import { isTaitoFirstSatSession } from "./session-schedule.ts";
import { isXavierSatCapabilitySession } from "./xavier-sat-capability-session.ts";
import { planAutogeneratedSatPrework } from "./autogenerated-sat-prework-plan.ts";

export { planAutogeneratedSatPrework } from "./autogenerated-sat-prework-plan.ts";

export async function liveSessionPreworkQuestionCount(sessionId: string): Promise<{
  assignmentId: string | null;
  questionCount: number;
}> {
  const rows = await db
    .select({
      id: assignmentsTable.id,
      status: assignmentsTable.status,
    })
    .from(assignmentsTable)
    .where(
      and(
        eq(assignmentsTable.sessionId, sessionId),
        eq(assignmentsTable.deliveryPhase, "before_session"),
      ),
    );
  let best = { assignmentId: null as string | null, questionCount: 0 };
  for (const row of rows) {
    if (row.status === "archived") continue;
    const [{ count }] = await db
      .select({ count: sql<number>`count(*)` })
      .from(assignmentQuestionsTable)
      .where(eq(assignmentQuestionsTable.assignmentId, row.id));
    const questionCount = Number(count);
    if (questionCount > best.questionCount) {
      best = { assignmentId: row.id, questionCount };
    }
  }
  return best;
}

export async function ensureAutogeneratedSatPrework(
  sessionId: string,
  actorUserId?: string | null,
): Promise<
  | { skipped: true; reason: string; assignmentId?: string | null }
  | Awaited<ReturnType<typeof assignPreworkFromBank>>
> {
  const [session] = await db
    .select()
    .from(sessionsTable)
    .where(eq(sessionsTable.id, sessionId))
    .limit(1);
  if (!session) {
    return { skipped: true, reason: "session-not-found" };
  }
  const existing = await liveSessionPreworkQuestionCount(session.id);
  const planned = planAutogeneratedSatPrework({
    subject: session.subject,
    existingLiveQuestionCount: existing.questionCount,
    isTaitoFirstSat: isTaitoFirstSatSession(session),
    isXavierCapability: isXavierSatCapabilitySession(session),
  });
  if (planned.action === "skip") {
    return {
      skipped: true,
      reason: planned.reason,
      assignmentId: existing.assignmentId,
    };
  }
  try {
    return await assignPreworkFromBank({
      sessionId: session.id,
      actorUserId,
      homeworkKind: planned.homeworkKind,
      skipArchiveExisting: true,
      mcqOnly: planned.homeworkKind === "routine",
    });
  } catch {
    return {
      skipped: true,
      reason: "bank-unavailable",
      assignmentId: existing.assignmentId,
    };
  }
}
