import { and, asc, eq, sql } from "drizzle-orm";
import {
  assignmentQuestionsTable,
  assignmentsTable,
  bankQuestionsTable,
  db,
  examSourceCollectionsTable,
  sessionPreworkPlansTable,
  sessionsTable,
} from "@workspace/db";
import {
  englishDiagnosticTimeLimitMinutes,
  englishRoutineTimeLimitMinutes,
  planAutogeneratedEnglishPrework,
} from "./autogenerated-english-prework-plan.ts";
import {
  IELTS_STYLE_COLLECTION_NOTES,
  IELTS_STYLE_COLLECTION_SLUG,
  IELTS_STYLE_COLLECTION_TITLE,
  IELTS_STYLE_COPYRIGHT_NOTICE,
  IELTS_STYLE_EXAM_FAMILY,
  IELTS_STYLE_SOURCE_KIND,
  IELTS_STYLE_VARIANT,
  IELTS_STYLE_WRITING_TASKS,
  ieltsStyleReadingItems,
} from "./ielts-style-bank-content.ts";
import {
  canAssignCleanEnglishQuizSet,
  ieltsStyleSourceKey,
  isIeltsStyleBankRow,
  selectIeltsStylePreworkItems,
} from "./ielts-style-bank-select.ts";
import { materializeBankQuestion } from "./sat-bank-service.ts";
import {
  isEnglishSessionSubject,
  isTaitoFirstEnglishSession,
  taitoEnglishSessionIndex,
} from "./session-schedule.ts";

export {
  IELTS_STYLE_COLLECTION_SLUG,
  IELTS_STYLE_COLLECTION_TITLE,
  IELTS_STYLE_COPYRIGHT_NOTICE,
  IELTS_STYLE_EXAM_FAMILY,
  IELTS_STYLE_SOURCE_KIND,
};
export {
  IELTS_STYLE_DIAGNOSTIC_COUNT,
  IELTS_STYLE_ROUTINE_COUNT,
  canAssignCleanEnglishQuizSet,
  ieltsStyleSourceKey,
  isIeltsStyleBankRow,
  selectIeltsStylePreworkItems,
} from "./ielts-style-bank-select.ts";

function readingBankValues() {
  return ieltsStyleReadingItems().map((item, index) => {
    const questionNumber = index + 1;
    return {
      sourceKey: ieltsStyleSourceKey({
        section: "reading",
        module: item.module,
        questionNumber,
      }),
      examFamily: IELTS_STYLE_EXAM_FAMILY,
      examVariant: IELTS_STYLE_VARIANT,
      practiceTestNumber: 1,
      formCode: item.set,
      section: "reading",
      module: item.module,
      questionNumber,
      position: questionNumber,
      prompt: item.prompt,
      stimulus: item.stimulus,
      choices: item.choices,
      correctAnswer: item.correctAnswer,
      officialExplanation: item.explanation,
      figures: [],
      scoring: { autoScore: true, originalIeltsStyle: true },
      skill: item.skill,
      domain: item.domain,
      difficulty: item.difficulty,
      questionType: "mcq",
      estimatedSeconds: item.estimatedSeconds,
      sourceKind: IELTS_STYLE_SOURCE_KIND,
      extractGaps: {},
      sourceFiles: {
        origin: "in-repo-original",
        passageId: item.passageId,
        set: item.set,
        notice: IELTS_STYLE_COPYRIGHT_NOTICE,
      },
    };
  });
}

function writingBankValues() {
  return IELTS_STYLE_WRITING_TASKS.map((task, index) => {
    const questionNumber = index + 1;
    return {
      sourceKey: ieltsStyleSourceKey({
        section: "writing",
        module: 4,
        questionNumber,
      }),
      examFamily: IELTS_STYLE_EXAM_FAMILY,
      examVariant: IELTS_STYLE_VARIANT,
      practiceTestNumber: 1,
      formCode: "writing",
      section: "writing",
      module: 4,
      questionNumber,
      position: 100 + questionNumber,
      prompt: task.prompt,
      stimulus: task.stimulus,
      choices: [],
      correctAnswer: "tutor-review",
      officialExplanation: task.explanation,
      figures: [],
      scoring: { autoScore: false, originalIeltsStyle: true },
      skill: task.skill,
      domain: task.domain,
      difficulty: task.difficulty,
      questionType: "writing_task",
      estimatedSeconds: task.estimatedSeconds,
      sourceKind: IELTS_STYLE_SOURCE_KIND,
      extractGaps: { missingChoices: true },
      sourceFiles: {
        origin: "in-repo-original",
        taskId: task.id,
        notice: IELTS_STYLE_COPYRIGHT_NOTICE,
      },
    };
  });
}

async function ensureIeltsStyleCollection(): Promise<string> {
  const [existing] = await db
    .select()
    .from(examSourceCollectionsTable)
    .where(eq(examSourceCollectionsTable.slug, IELTS_STYLE_COLLECTION_SLUG))
    .limit(1);
  if (existing) {
    await db
      .update(examSourceCollectionsTable)
      .set({
        title: IELTS_STYLE_COLLECTION_TITLE,
        notes: IELTS_STYLE_COLLECTION_NOTES,
        examFamily: IELTS_STYLE_EXAM_FAMILY,
        examVariant: IELTS_STYLE_VARIANT,
        extractStatus: "complete",
        updatedAt: new Date(),
      })
      .where(eq(examSourceCollectionsTable.id, existing.id));
    return existing.id;
  }
  const [created] = await db
    .insert(examSourceCollectionsTable)
    .values({
      examFamily: IELTS_STYLE_EXAM_FAMILY,
      examVariant: IELTS_STYLE_VARIANT,
      practiceTestNumber: 1,
      title: IELTS_STYLE_COLLECTION_TITLE,
      slug: IELTS_STYLE_COLLECTION_SLUG,
      notes: IELTS_STYLE_COLLECTION_NOTES,
      extractStatus: "complete",
    })
    .returning({ id: examSourceCollectionsTable.id });
  return created!.id;
}

export async function ensureIeltsStyleBankImported(): Promise<{
  inserted: number;
  updated: number;
  collectionId: string;
}> {
  const collectionId = await ensureIeltsStyleCollection();
  const records = [...readingBankValues(), ...writingBankValues()];
  let inserted = 0;
  let updated = 0;
  for (const record of records) {
    const values = { ...record, collectionId, updatedAt: new Date() };
    const [existing] = await db
      .select({ id: bankQuestionsTable.id })
      .from(bankQuestionsTable)
      .where(eq(bankQuestionsTable.sourceKey, record.sourceKey))
      .limit(1);
    if (existing) {
      await db
        .update(bankQuestionsTable)
        .set(values)
        .where(eq(bankQuestionsTable.id, existing.id));
      updated += 1;
    } else {
      await db.insert(bankQuestionsTable).values(values);
      inserted += 1;
    }
  }
  return { inserted, updated, collectionId };
}

function bankRowForQuality(row: typeof bankQuestionsTable.$inferSelect) {
  return {
    id: row.id,
    prompt: row.prompt,
    stimulus: row.stimulus,
    choices: Array.isArray(row.choices) ? row.choices : [],
    questionType: row.questionType,
    correctAnswer: row.correctAnswer,
    section: row.section,
    subject: "IELTS Reading",
    domain: row.domain,
    figures: [],
    extractGaps: (row.extractGaps ?? {}) as Record<string, unknown>,
  };
}

async function archiveSessionPrework(sessionId: string) {
  const existing = await db
    .select()
    .from(assignmentsTable)
    .where(
      and(
        eq(assignmentsTable.sessionId, sessionId),
        eq(assignmentsTable.deliveryPhase, "before_session"),
      ),
    );
  for (const row of existing) {
    if (row.status === "archived") continue;
    await db
      .update(assignmentsTable)
      .set({ status: "archived" })
      .where(eq(assignmentsTable.id, row.id));
  }
}

export async function assignEnglishPreworkFromBank(input: {
  sessionId: string;
  actorUserId?: string | null;
  collectionId?: string | null;
  bankQuestionIds?: string[];
  homeworkKind?: "diagnostic" | "routine";
  skipArchiveExisting?: boolean;
  setIndex?: number;
}): Promise<{
  planId: string;
  assignmentId: string;
  homeworkKind: "diagnostic" | "routine";
  targetMinutes: number;
  estimatedSeconds: number;
  questionCount: number;
  withinTolerance: boolean;
  extractIncomplete: boolean;
  composition: null;
  assignBlocked: boolean;
}> {
  const [session] = await db
    .select()
    .from(sessionsTable)
    .where(eq(sessionsTable.id, input.sessionId))
    .limit(1);
  if (!session) {
    throw Object.assign(new Error("Session not found"), { status: 404 });
  }
  if (!isEnglishSessionSubject(session.subject)) {
    throw Object.assign(
      new Error("IELTS-style pre-work can only be assigned to English or IELTS sessions."),
      { status: 409 },
    );
  }
  const seeded = await ensureIeltsStyleBankImported();
  const homeworkKind = input.homeworkKind ?? "routine";
  const setIndex =
    input.setIndex ??
    (homeworkKind === "diagnostic"
      ? 0
      : Math.max(1, taitoEnglishSessionIndex(session)));
  if (input.collectionId && input.collectionId !== seeded.collectionId) {
    throw Object.assign(
      new Error(
        "This English session expects the original IELTS-style practice collection, not a College Board SAT/PSAT extract.",
      ),
      { status: 409 },
    );
  }
  let pool = await db
    .select()
    .from(bankQuestionsTable)
    .where(eq(bankQuestionsTable.examFamily, IELTS_STYLE_EXAM_FAMILY))
    .orderBy(asc(bankQuestionsTable.position));
  pool = pool.filter((row) => isIeltsStyleBankRow(row));
  if (input.bankQuestionIds?.length) {
    const allowed = new Set(input.bankQuestionIds);
    pool = pool.filter((row) => allowed.has(row.id));
  }
  const selectedRows = selectIeltsStylePreworkItems(pool, { homeworkKind, setIndex });
  const qualityRows = selectedRows.map(bankRowForQuality);
  if (!canAssignCleanEnglishQuizSet(qualityRows)) {
    throw Object.assign(
      new Error(
        "English pre-work assign blocked: the original IELTS-style bank has no clean Reading MCQ set yet.",
      ),
      { status: 409, assignBlocked: true },
    );
  }
  const estimatedSeconds = selectedRows.reduce(
    (sum, row) => sum + Math.max(0, Number(row.estimatedSeconds) || 0),
    0,
  );
  const resolvedMinutes =
    homeworkKind === "diagnostic"
      ? englishDiagnosticTimeLimitMinutes(selectedRows.length)
      : englishRoutineTimeLimitMinutes(selectedRows.length);
  if (!input.skipArchiveExisting) {
    await archiveSessionPrework(session.id);
  }
  const title =
    homeworkKind === "diagnostic"
      ? `IELTS-style diagnostic reading — ${session.title}`
      : `IELTS-style reading pre-work — ${session.title}`;
  const [assignment] = await db
    .insert(assignmentsTable)
    .values({
      courseId: session.courseId,
      sessionId: session.id,
      deliveryPhase: "before_session",
      title,
      subject: session.subject || "IELTS",
      instructions:
        homeworkKind === "diagnostic"
          ? `${IELTS_STYLE_COPYRIGHT_NOTICE} Complete this short Reading set before the session. Accuracy is recorded. Writing tasks stay in the bank for tutor review and are not auto-scored.`
          : `${IELTS_STYLE_COPYRIGHT_NOTICE} Short Reading MCQ pre-work for this English session. This is not an official IELTS score.`,
      status: "published",
      timeLimitMinutes: resolvedMinutes,
      maxAttempts: 1,
    })
    .returning();
  for (const [index, bank] of selectedRows.entries()) {
    const questionId = await materializeBankQuestion(bank.id);
    await db.insert(assignmentQuestionsTable).values({
      assignmentId: assignment!.id,
      questionId,
      position: index,
      predictionFirst: false,
    });
  }
  const [existingPlan] = await db
    .select()
    .from(sessionPreworkPlansTable)
    .where(eq(sessionPreworkPlansTable.sessionId, session.id))
    .limit(1);
  const planValues = {
    assignmentId: assignment!.id,
    homeworkKind,
    targetMinutes: resolvedMinutes,
    estimatedSeconds,
    status: "assigned",
    createdByUserId: input.actorUserId ?? null,
    updatedAt: new Date(),
  };
  const plan = existingPlan
    ? (
        await db
          .update(sessionPreworkPlansTable)
          .set(planValues)
          .where(eq(sessionPreworkPlansTable.id, existingPlan.id))
          .returning()
      )[0]!
    : (
        await db
          .insert(sessionPreworkPlansTable)
          .values({ sessionId: session.id, ...planValues })
          .returning()
      )[0]!;
  await db
    .update(sessionsTable)
    .set({ hasHomework: true, updatedAt: new Date() })
    .where(eq(sessionsTable.id, session.id));
  return {
    planId: plan.id,
    assignmentId: assignment!.id,
    homeworkKind,
    targetMinutes: resolvedMinutes,
    estimatedSeconds,
    questionCount: selectedRows.length,
    withinTolerance: selectedRows.length > 0,
    extractIncomplete: false,
    composition: null,
    assignBlocked: false,
  };
}

export async function liveEnglishSessionIdsForCourse(courseId: string): Promise<string[]> {
  const rows = await db
    .select({
      id: sessionsTable.id,
      subject: sessionsTable.subject,
      status: sessionsTable.status,
      bookingStatus: sessionsTable.bookingStatus,
    })
    .from(sessionsTable)
    .where(eq(sessionsTable.courseId, courseId));
  return rows
    .filter(
      (row) =>
        isEnglishSessionSubject(row.subject) &&
        row.status !== "archived" &&
        row.bookingStatus !== "cancelled",
    )
    .map((row) => row.id);
}

export async function ensureAutogeneratedEnglishPrework(
  sessionId: string,
  actorUserId?: string | null,
): Promise<
  | { skipped: true; reason: string; assignmentId?: string | null }
  | Awaited<ReturnType<typeof assignEnglishPreworkFromBank>>
> {
  const [session] = await db
    .select()
    .from(sessionsTable)
    .where(eq(sessionsTable.id, sessionId))
    .limit(1);
  if (!session) {
    return { skipped: true, reason: "session-not-found" };
  }
  const [{ count }] = await db
    .select({ count: sql<number>`count(*)` })
    .from(assignmentQuestionsTable)
    .innerJoin(assignmentsTable, eq(assignmentsTable.id, assignmentQuestionsTable.assignmentId))
    .where(
      and(
        eq(assignmentsTable.sessionId, session.id),
        eq(assignmentsTable.deliveryPhase, "before_session"),
        sql`${assignmentsTable.status} <> 'archived'`,
      ),
    );
  const planned = planAutogeneratedEnglishPrework({
    subject: session.subject,
    existingLiveQuestionCount: Number(count),
    isTaitoFirstEnglish: isTaitoFirstEnglishSession(session),
    taitoEnglishIndex: taitoEnglishSessionIndex(session),
  });
  if (planned.action === "skip") {
    return { skipped: true, reason: planned.reason };
  }
  try {
    return await assignEnglishPreworkFromBank({
      sessionId: session.id,
      actorUserId,
      homeworkKind: planned.homeworkKind,
      setIndex: planned.setIndex,
      skipArchiveExisting: true,
    });
  } catch {
    return { skipped: true, reason: "bank-unavailable" };
  }
}

export async function ensureTaitoEnglishSessionPrework(
  courseId: string,
  actorUserId?: string | null,
): Promise<number> {
  const sessionIds = await liveEnglishSessionIdsForCourse(courseId);
  let assigned = 0;
  for (const sessionId of sessionIds) {
    const result = await ensureAutogeneratedEnglishPrework(sessionId, actorUserId);
    if (!("skipped" in result) || result.skipped !== true) assigned += 1;
  }
  return assigned;
}

export function homeworkKindForSessionPreworkReset(input: {
  subject: string;
  isTaitoFirstSat: boolean;
  isXavierCapability: boolean;
  isTaitoFirstEnglish: boolean;
  taitoEnglishIndex?: number;
  satKind: "diagnostic" | "routine" | null;
}): "diagnostic" | "routine" | null {
  const english = planAutogeneratedEnglishPrework({
    subject: input.subject,
    existingLiveQuestionCount: 0,
    isTaitoFirstEnglish: input.isTaitoFirstEnglish,
    taitoEnglishIndex: input.taitoEnglishIndex,
  });
  if (english.action === "assign") return english.homeworkKind;
  return input.satKind;
}

export { ieltsStyleReadingItems };
