import assert from "node:assert/strict";
import test from "node:test";
import {
  extrasToArchiveForKind,
  inferSessionPreworkKind,
  isLiveBeforeSessionHomework,
  isSeededOrAutogenPreworkTitle,
  pickLiveSessionPreworkKeeper,
  sessionPreworkSubjectFamily,
  shouldSkipAutogeneratedPreworkAssign,
} from "./session-prework-dedupe.ts";

test("already has live homework of the same kind → skip, even when the row is empty", () => {
  const emptyDiagnostic = {
    id: "empty-ielts-diagnostic",
    title: "IELTS-style diagnostic reading — Taito’s English Session with Nika",
    status: "published",
    deliveryPhase: "before_session",
    homeworkKind: "diagnostic" as const,
    questionCount: 0,
    attemptCount: 0,
  };
  assert.deepEqual(
    shouldSkipAutogeneratedPreworkAssign({
      plannedKind: "diagnostic",
      liveHomework: [emptyDiagnostic],
    }),
    {
      skip: true,
      reason: "already-assigned",
      assignmentId: "empty-ielts-diagnostic",
    },
  );
  assert.deepEqual(
    shouldSkipAutogeneratedPreworkAssign({
      plannedKind: "routine",
      liveHomework: [
        {
          id: "sat-grammar",
          title: "SAT Homework — Grammar and Boundaries",
          status: "published",
          deliveryPhase: "before_session",
          questionCount: 0,
        },
      ],
    }),
    { skip: true, reason: "already-assigned", assignmentId: "sat-grammar" },
  );
});

test("archived or during-session rows do not block a new before-session insert", () => {
  assert.equal(
    shouldSkipAutogeneratedPreworkAssign({
      plannedKind: "routine",
      liveHomework: [
        {
          id: "archived",
          title: "IELTS-style reading pre-work — Taito’s English Session with Nika",
          status: "archived",
          deliveryPhase: "before_session",
          homeworkKind: "routine",
          questionCount: 12,
        },
        {
          id: "during",
          title: "In-session homework completion",
          status: "published",
          deliveryPhase: "during_session",
          homeworkKind: "routine",
          questionCount: 8,
        },
      ],
    }).skip,
    false,
  );
});

test("a live diagnostic does not skip a planned routine, and the reverse", () => {
  assert.equal(
    shouldSkipAutogeneratedPreworkAssign({
      plannedKind: "routine",
      liveHomework: [
        {
          id: "diagnostic",
          title: "IELTS-style diagnostic reading — Taito’s English Session with Nika",
          homeworkKind: "diagnostic",
          status: "published",
          deliveryPhase: "before_session",
          questionCount: 24,
        },
      ],
    }).skip,
    false,
  );
  assert.equal(
    shouldSkipAutogeneratedPreworkAssign({
      plannedKind: "diagnostic",
      liveHomework: [
        {
          id: "routine",
          title: "SAT Homework — Grammar and Boundaries",
          status: "published",
          deliveryPhase: "before_session",
          questionCount: 4,
        },
      ],
    }).skip,
    false,
  );
});

test("keeper prefers the newest complete assignment over empties and older completes", () => {
  const keeper = pickLiveSessionPreworkKeeper([
    {
      id: "empty-new",
      title: "IELTS-style reading pre-work — Taito’s English Session with Nika",
      questionCount: 0,
      createdAt: "2026-09-19T18:00:00.000Z",
    },
    {
      id: "complete-old",
      title: "IELTS-style reading pre-work — Taito’s English Session with Nika",
      questionCount: 12,
      createdAt: "2026-09-18T12:00:00.000Z",
      attemptCount: 0,
    },
    {
      id: "complete-new",
      title: "IELTS-style reading pre-work — Taito’s English Session with Nika",
      questionCount: 12,
      createdAt: "2026-09-19T12:00:00.000Z",
      attemptCount: 1,
    },
  ]);
  assert.equal(keeper?.id, "complete-new");
  const { extras } = extrasToArchiveForKind(
    [
      {
        id: "complete-new",
        title: "IELTS-style reading pre-work — Taito’s English Session with Nika",
        status: "published",
        deliveryPhase: "before_session",
        questionCount: 12,
        createdAt: "2026-09-19T12:00:00.000Z",
      },
      {
        id: "empty-new",
        title: "IELTS-style reading pre-work — Taito’s English Session with Nika",
        status: "published",
        deliveryPhase: "before_session",
        questionCount: 0,
        createdAt: "2026-09-19T18:00:00.000Z",
      },
    ],
    "routine",
  );
  assert.deepEqual(
    extras.map((row) => row.id),
    ["empty-new"],
  );
});

test("title inference treats IELTS diagnostic / SAT homework seed copy as the right kind", () => {
  assert.equal(
    inferSessionPreworkKind({
      title: "IELTS-style diagnostic reading — Taito’s English Session with Nika",
    }),
    "diagnostic",
  );
  assert.equal(
    inferSessionPreworkKind({ title: "SAT Homework — Grammar and Boundaries" }),
    "routine",
  );
  assert.equal(isLiveBeforeSessionHomework({ status: "published" }), true);
  assert.equal(isSeededOrAutogenPreworkTitle("SAT pre-work (30–50 questions) — Taito"), true);
  assert.equal(isSeededOrAutogenPreworkTitle("Hard-question bank — leftover time"), false);
  assert.equal(
    sessionPreworkSubjectFamily({ title: "IELTS-style reading pre-work — Taito" }),
    "ielts",
  );
  assert.equal(
    sessionPreworkSubjectFamily({ title: "SAT Homework — Grammar and Boundaries" }),
    "sat",
  );
});
