import { and, eq, inArray, sql } from "drizzle-orm";
import {
  assignmentQuestionsTable,
  assignmentsTable,
  attemptsTable,
  coursesTable,
  db,
  sessionPreworkPlansTable,
  sessionsTable,
} from "@workspace/db";
import { isXavierSatCapabilityCopy } from "./assignment-visibility.ts";
import {
  extrasToArchiveForKind,
  inferSessionPreworkKind,
  isLiveBeforeSessionHomework,
  pickLiveSessionPreworkKeeper,
  shouldSkipAutogeneratedPreworkAssign,
  type LiveSessionPreworkCandidate,
  type SessionPreworkKind,
} from "./session-prework-dedupe.ts";

const FALL_SAT_COURSE_TITLE = "Fall 2026 SAT & IELTS";

export type LiveSessionPreworkRow = LiveSessionPreworkCandidate & {
  id: string;
  title: string;
  status: string;
  deliveryPhase: string;
  subject: string;
  sessionId: string;
  createdAt: Date;
  questionCount: number;
  attemptCount: number;
  homeworkKind: SessionPreworkKind | null;
};

export async function withSessionPreworkLock<T>(
  sessionId: string,
  work: () => Promise<T>,
): Promise<T> {
  await db.execute(sql`select pg_advisory_lock(hashtext(${`session-prework:${sessionId}`}))`);
  try {
    return await work();
  } finally {
    await db.execute(sql`select pg_advisory_unlock(hashtext(${`session-prework:${sessionId}`}))`);
  }
}

export async function listLiveBeforeSessionHomework(
  sessionId: string,
): Promise<LiveSessionPreworkRow[]> {
  const rows = await db
    .select({
      id: assignmentsTable.id,
      title: assignmentsTable.title,
      status: assignmentsTable.status,
      deliveryPhase: assignmentsTable.deliveryPhase,
      subject: assignmentsTable.subject,
      sessionId: assignmentsTable.sessionId,
      createdAt: assignmentsTable.createdAt,
    })
    .from(assignmentsTable)
    .where(
      and(
        eq(assignmentsTable.sessionId, sessionId),
        eq(assignmentsTable.deliveryPhase, "before_session"),
      ),
    );
  const [plan] = await db
    .select({
      assignmentId: sessionPreworkPlansTable.assignmentId,
      homeworkKind: sessionPreworkPlansTable.homeworkKind,
    })
    .from(sessionPreworkPlansTable)
    .where(eq(sessionPreworkPlansTable.sessionId, sessionId))
    .limit(1);
  const live = rows.filter((row) => isLiveBeforeSessionHomework(row));
  const result: LiveSessionPreworkRow[] = [];
  for (const row of live) {
    const [{ count }] = await db
      .select({ count: sql<number>`count(*)` })
      .from(assignmentQuestionsTable)
      .where(eq(assignmentQuestionsTable.assignmentId, row.id));
    const [{ count: attempts }] = await db
      .select({ count: sql<number>`count(*)` })
      .from(attemptsTable)
      .where(eq(attemptsTable.assignmentId, row.id));
    const plannedKind =
      plan?.assignmentId === row.id &&
      (plan.homeworkKind === "diagnostic" || plan.homeworkKind === "routine")
        ? plan.homeworkKind
        : null;
    result.push({
      ...row,
      sessionId: row.sessionId ?? sessionId,
      questionCount: Number(count),
      attemptCount: Number(attempts),
      homeworkKind: plannedKind ?? inferSessionPreworkKind(row),
    });
  }
  return result;
}

export async function liveSessionPreworkQuestionCount(sessionId: string): Promise<{
  assignmentId: string | null;
  questionCount: number;
  liveCount: number;
}> {
  const live = await listLiveBeforeSessionHomework(sessionId);
  const keeper = pickLiveSessionPreworkKeeper(live);
  return {
    assignmentId: keeper?.id ?? null,
    questionCount: keeper?.questionCount ?? 0,
    liveCount: live.length,
  };
}

export async function existingLivePreworkAssignResult(
  assignmentId: string,
  homeworkKind: SessionPreworkKind,
): Promise<{
  planId: string;
  assignmentId: string;
  homeworkKind: SessionPreworkKind;
  targetMinutes: number;
  estimatedSeconds: number;
  questionCount: number;
  withinTolerance: boolean;
  extractIncomplete: boolean;
  composition: null;
  assignBlocked: boolean;
}> {
  const [assignment] = await db
    .select({
      id: assignmentsTable.id,
      sessionId: assignmentsTable.sessionId,
      timeLimitMinutes: assignmentsTable.timeLimitMinutes,
    })
    .from(assignmentsTable)
    .where(eq(assignmentsTable.id, assignmentId))
    .limit(1);
  const [{ count }] = await db
    .select({ count: sql<number>`count(*)` })
    .from(assignmentQuestionsTable)
    .where(eq(assignmentQuestionsTable.assignmentId, assignmentId));
  const [plan] = assignment?.sessionId
    ? await db
        .select()
        .from(sessionPreworkPlansTable)
        .where(eq(sessionPreworkPlansTable.sessionId, assignment.sessionId))
        .limit(1)
    : [];
  const targetMinutes = plan?.targetMinutes ?? assignment?.timeLimitMinutes ?? 30;
  return {
    planId: plan?.id ?? "",
    assignmentId,
    homeworkKind: plan?.homeworkKind === "diagnostic" || plan?.homeworkKind === "routine"
      ? plan.homeworkKind
      : homeworkKind,
    targetMinutes,
    estimatedSeconds: plan?.estimatedSeconds ?? targetMinutes * 60,
    questionCount: Number(count),
    withinTolerance: Number(count) > 0,
    extractIncomplete: false,
    composition: null,
    assignBlocked: false,
  };
}

export async function reuseLivePreworkIfPresent(input: {
  sessionId: string;
  plannedKind: SessionPreworkKind;
}): Promise<Awaited<ReturnType<typeof existingLivePreworkAssignResult>> | null> {
  const live = await listLiveBeforeSessionHomework(input.sessionId);
  const decision = shouldSkipAutogeneratedPreworkAssign({
    plannedKind: input.plannedKind,
    liveHomework: live,
  });
  if (!decision.skip || !decision.assignmentId) return null;
  return existingLivePreworkAssignResult(decision.assignmentId, input.plannedKind);
}

export type ArchiveDuplicateSessionPreworkOptions = {
  courseId?: string;
  dryRun?: boolean;
};

export type ArchiveDuplicateSessionPreworkSessionResult = {
  sessionId: string;
  title: string;
  subject: string;
  dateTime: string;
  kind: SessionPreworkKind;
  keeperId: string | null;
  keeperTitle: string | null;
  keeperQuestionCount: number;
  archivedIds: string[];
  archivedTitles: string[];
  dryRun: boolean;
};

export type ArchiveDuplicateSessionPreworkResult = {
  ok: boolean;
  dryRun: boolean;
  courseId: string | null;
  sessions: ArchiveDuplicateSessionPreworkSessionResult[];
  archivedAssignments: number;
};

async function resolveCourseId(courseId?: string): Promise<string | null> {
  if (courseId) return courseId;
  const [course] = await db
    .select({ id: coursesTable.id })
    .from(coursesTable)
    .where(eq(coursesTable.title, FALL_SAT_COURSE_TITLE))
    .limit(1);
  return course?.id ?? null;
}

export async function archiveExtraLiveSessionPrework(
  options: ArchiveDuplicateSessionPreworkOptions = {},
): Promise<ArchiveDuplicateSessionPreworkResult> {
  const dryRun = Boolean(options.dryRun);
  const courseId = await resolveCourseId(options.courseId);
  if (!courseId) {
    return {
      ok: false,
      dryRun,
      courseId: null,
      sessions: [],
      archivedAssignments: 0,
    };
  }
  const sessions = await db
    .select()
    .from(sessionsTable)
    .where(eq(sessionsTable.courseId, courseId));
  const results: ArchiveDuplicateSessionPreworkSessionResult[] = [];
  let archivedAssignments = 0;
  for (const session of sessions) {
    if (session.status === "archived" || session.bookingStatus === "cancelled") continue;
    if (isXavierSatCapabilityCopy(session.title)) continue;
    const live = await listLiveBeforeSessionHomework(session.id);
    for (const kind of ["diagnostic", "routine"] as const) {
      const { keeper, extras } = extrasToArchiveForKind(live, kind);
      if (!keeper || extras.length === 0) continue;
      const archivedIds: string[] = [];
      if (!dryRun) {
        await db
          .update(assignmentsTable)
          .set({ status: "archived" })
          .where(
            inArray(
              assignmentsTable.id,
              extras.map((row) => row.id),
            ),
          );
        const [plan] = await db
          .select({ id: sessionPreworkPlansTable.id })
          .from(sessionPreworkPlansTable)
          .where(eq(sessionPreworkPlansTable.sessionId, session.id))
          .limit(1);
        if (plan) {
          await db
            .update(sessionPreworkPlansTable)
            .set({ assignmentId: keeper.id, homeworkKind: kind, updatedAt: new Date() })
            .where(eq(sessionPreworkPlansTable.id, plan.id));
        }
      }
      archivedIds.push(...extras.map((row) => row.id));
      archivedAssignments += extras.length;
      results.push({
        sessionId: session.id,
        title: session.title,
        subject: session.subject,
        dateTime: session.dateTime.toISOString(),
        kind,
        keeperId: keeper.id,
        keeperTitle: keeper.title,
        keeperQuestionCount: keeper.questionCount,
        archivedIds,
        archivedTitles: extras.map((row) => row.title),
        dryRun,
      });
    }
  }
  return {
    ok: true,
    dryRun,
    courseId,
    sessions: results,
    archivedAssignments,
  };
}
