import { isFullLengthDiagnosticAssignment } from "./assignment-visibility.ts";
import { isPostSessionFollowUpTitle } from "./post-session-follow-up.ts";

export type SessionPreworkKind = "diagnostic" | "routine";

export type LiveSessionPreworkCandidate = {
  id: string;
  title?: string | null;
  status?: string | null;
  deliveryPhase?: string | null;
  homeworkKind?: string | null;
  questionCount?: number | null;
  attemptCount?: number | null;
  createdAt?: Date | string | number | null;
  subject?: string | null;
};

export function isLiveBeforeSessionHomework(input: {
  status?: string | null;
  deliveryPhase?: string | null;
  title?: string | null;
}): boolean {
  if (input.status === "archived") return false;
  if (isPostSessionFollowUpTitle(input.title)) return false;
  const phase = input.deliveryPhase ?? "before_session";
  return phase === "before_session";
}

export function inferSessionPreworkKind(input: {
  title?: string | null;
  homeworkKind?: string | null;
  questionCount?: number | null;
}): SessionPreworkKind {
  if (input.homeworkKind === "diagnostic" || input.homeworkKind === "routine") {
    return input.homeworkKind;
  }
  if (
    isFullLengthDiagnosticAssignment({
      title: input.title,
      homeworkKind: input.homeworkKind,
      questionCount: input.questionCount,
    })
  ) {
    return "diagnostic";
  }
  const title = input.title?.trim().toLowerCase() ?? "";
  if (title.includes("diagnostic")) return "diagnostic";
  return "routine";
}

export function sessionPreworkSubjectFamily(
  input: { title?: string | null; subject?: string | null },
): "sat" | "ielts" | "other" {
  const blob = `${input.subject ?? ""} ${input.title ?? ""}`.trim().toLowerCase();
  if (blob.includes("ielts") || blob.includes("english")) return "ielts";
  if (blob.includes("sat") || blob.includes("psat")) return "sat";
  return "other";
}

/**
 * Interchangeable copies of one template.
 * Bank routine SAT ("SAT pre-work (30–50 questions)", "60-minute SAT pre-work")
 * is not the seeded topic set ("SAT Homework — Grammar and Boundaries") or an
 * IELTS-style reading assignment.
 */
export type SessionPreworkDedupeSlot =
  | "sat-bank-prework"
  | "sat-topic-homework"
  | "sat-diagnostic"
  | "ielts-prework";

export function sessionPreworkDedupeSlot(
  title?: string | null,
): SessionPreworkDedupeSlot | null {
  const normalized = title?.trim().toLowerCase() ?? "";
  if (!normalized) return null;
  if (
    normalized.includes("full-length sat diagnostic") ||
    normalized.includes("full sat practice diagnostic") ||
    normalized.includes("sat diagnostic")
  ) {
    return "sat-diagnostic";
  }
  if (normalized.includes("sat pre-work")) return "sat-bank-prework";
  if (normalized.includes("sat homework")) return "sat-topic-homework";
  if (normalized.includes("ielts-style")) return "ielts-prework";
  return null;
}

/** Seeded topic homework or autogen English/SAT pre-work titles Cos should not multiply within one slot. */
export function isSeededOrAutogenPreworkTitle(title?: string | null): boolean {
  return sessionPreworkDedupeSlot(title) !== null;
}

function createdAtMs(value: LiveSessionPreworkCandidate["createdAt"]): number {
  if (value instanceof Date) return value.getTime();
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value === "string" && value.trim()) {
    const parsed = Date.parse(value);
    return Number.isFinite(parsed) ? parsed : 0;
  }
  return 0;
}

/** Prefer a complete set (has questions), then the newest row, then any student work. */
export function pickLiveSessionPreworkKeeper<T extends LiveSessionPreworkCandidate>(
  rows: readonly T[],
): T | null {
  if (rows.length === 0) return null;
  return (
    [...rows].sort((left, right) => {
      const leftComplete = (left.questionCount ?? 0) > 0 ? 1 : 0;
      const rightComplete = (right.questionCount ?? 0) > 0 ? 1 : 0;
      if (rightComplete !== leftComplete) return rightComplete - leftComplete;
      const createdDelta = createdAtMs(right.createdAt) - createdAtMs(left.createdAt);
      if (createdDelta !== 0) return createdDelta;
      const attemptDelta = (right.attemptCount ?? 0) - (left.attemptCount ?? 0);
      if (attemptDelta !== 0) return attemptDelta;
      return right.id.localeCompare(left.id);
    })[0] ?? null
  );
}

export function liveSessionPreworkOfKind<T extends LiveSessionPreworkCandidate>(
  rows: readonly T[],
  kind: SessionPreworkKind,
): T[] {
  return rows.filter(
    (row) => isLiveBeforeSessionHomework(row) && inferSessionPreworkKind(row) === kind,
  );
}

/**
 * Fail-closed: a live before-session row of the same kind blocks another insert,
 * even when that row still has zero questions.
 */
export function shouldSkipAutogeneratedPreworkAssign(input: {
  plannedKind: SessionPreworkKind;
  liveHomework: readonly LiveSessionPreworkCandidate[];
}):
  | { skip: true; reason: "already-assigned"; assignmentId: string | null }
  | { skip: false } {
  const sameKind = liveSessionPreworkOfKind(input.liveHomework, input.plannedKind);
  if (sameKind.length === 0) return { skip: false };
  const keeper = pickLiveSessionPreworkKeeper(sameKind);
  return {
    skip: true,
    reason: "already-assigned",
    assignmentId: keeper?.id ?? sameKind[0]!.id,
  };
}

export function extrasToArchiveForKind<T extends LiveSessionPreworkCandidate>(
  rows: readonly T[],
  kind: SessionPreworkKind,
): { keeper: T | null; extras: T[] } {
  const sameKind = liveSessionPreworkOfKind(rows, kind);
  const keeper = pickLiveSessionPreworkKeeper(sameKind);
  return {
    keeper,
    extras: sameKind.filter((row) => row.id !== keeper?.id),
  };
}
