import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";

const hasDatabase = Boolean(process.env.DATABASE_URL?.trim());

test(
  "ensureAutogeneratedEnglishPrework skips when the session already has live homework",
  { skip: !hasDatabase },
  async () => {
    const { eq } = await import("drizzle-orm");
    const {
      assignmentsTable,
      coursesTable,
      db,
      sessionPreworkPlansTable,
      sessionsTable,
    } = await import("@workspace/db");
    const { taitoSessionDateTime } = await import("./session-schedule.ts");
    const { ensureAutogeneratedEnglishPrework } = await import("./ielts-style-bank.ts");

    const suffix = randomUUID();
    const [course] = await db
      .insert(coursesTable)
      .values({
        title: `English prework skip ${suffix}`,
        subject: "SAT & IELTS",
        term: "Fall 2026",
        status: "active",
      })
      .returning();
    const [session] = await db
      .insert(sessionsTable)
      .values({
        courseId: course!.id,
        dateTime: taitoSessionDateTime("2026-10-23"),
        timezone: "Asia/Tokyo",
        subject: "IELTS",
        title: "Taito’s English Session with Nika",
        status: "published",
        hasHomework: true,
      })
      .returning();
    const [existing] = await db
      .insert(assignmentsTable)
      .values({
        courseId: course!.id,
        sessionId: session!.id,
        deliveryPhase: "before_session",
        title: "IELTS-style diagnostic reading — Taito’s English Session with Nika",
        subject: "IELTS",
        instructions: "Empty published copy left by a failed assign.",
        status: "published",
        timeLimitMinutes: 30,
        maxAttempts: 1,
      })
      .returning();

    try {
      const first = await ensureAutogeneratedEnglishPrework(session!.id);
      assert.equal("skipped" in first && first.skipped, true);
      assert.equal("reason" in first ? first.reason : "", "already-assigned");
      if ("assignmentId" in first) {
        assert.equal(first.assignmentId, existing!.id);
      }

      const second = await ensureAutogeneratedEnglishPrework(session!.id);
      assert.equal("skipped" in second && second.skipped, true);

      const live = await db
        .select({ id: assignmentsTable.id, status: assignmentsTable.status })
        .from(assignmentsTable)
        .where(eq(assignmentsTable.sessionId, session!.id));
      assert.equal(live.filter((row) => row.status !== "archived").length, 1);
      assert.equal(live[0]?.id, existing!.id);
    } finally {
      await db
        .delete(sessionPreworkPlansTable)
        .where(eq(sessionPreworkPlansTable.sessionId, session!.id));
      await db.delete(assignmentsTable).where(eq(assignmentsTable.id, existing!.id));
      await db.delete(sessionsTable).where(eq(sessionsTable.id, session!.id));
      await db.delete(coursesTable).where(eq(coursesTable.id, course!.id));
    }
  },
);

test(
  "ensureAutogeneratedSatPrework skips a live SAT Homework routine even when it has 0 questions",
  { skip: !hasDatabase },
  async () => {
    const { eq } = await import("drizzle-orm");
    const { assignmentsTable, coursesTable, db, sessionsTable } = await import("@workspace/db");
    const { taitoSessionDateTime } = await import("./session-schedule.ts");
    const { ensureAutogeneratedSatPrework } = await import("./autogenerated-sat-prework.ts");

    const suffix = randomUUID();
    const [course] = await db
      .insert(coursesTable)
      .values({
        title: `SAT prework skip ${suffix}`,
        subject: "SAT",
        term: "Fall 2026",
        status: "active",
      })
      .returning();
    const [session] = await db
      .insert(sessionsTable)
      .values({
        courseId: course!.id,
        dateTime: taitoSessionDateTime("2026-10-09"),
        timezone: "Asia/Tokyo",
        subject: "SAT",
        title: "Taito’s SAT Session with Eunice",
        status: "published",
        hasHomework: true,
      })
      .returning();
    const [existing] = await db
      .insert(assignmentsTable)
      .values({
        courseId: course!.id,
        sessionId: session!.id,
        deliveryPhase: "before_session",
        title: "SAT Homework — Grammar and Boundaries",
        subject: "SAT Reading & Writing",
        instructions: "Seeded routine.",
        status: "published",
        timeLimitMinutes: 15,
        maxAttempts: 2,
      })
      .returning();

    try {
      const result = await ensureAutogeneratedSatPrework(session!.id);
      assert.equal("skipped" in result && result.skipped, true);
      assert.equal("reason" in result ? result.reason : "", "already-assigned");
      const live = await db
        .select({ id: assignmentsTable.id, status: assignmentsTable.status })
        .from(assignmentsTable)
        .where(eq(assignmentsTable.sessionId, session!.id));
      assert.equal(live.filter((row) => row.status !== "archived").length, 1);
      assert.equal(live[0]?.id, existing!.id);
    } finally {
      await db.delete(assignmentsTable).where(eq(assignmentsTable.id, existing!.id));
      await db.delete(sessionsTable).where(eq(sessionsTable.id, session!.id));
      await db.delete(coursesTable).where(eq(coursesTable.id, course!.id));
    }
  },
);

test(
  "archiveExtraLiveSessionPrework keeps the newest complete English copy",
  { skip: !hasDatabase },
  async () => {
    const { eq, inArray } = await import("drizzle-orm");
    const {
      assignmentQuestionsTable,
      assignmentsTable,
      coursesTable,
      db,
      questionsTable,
      sessionPreworkPlansTable,
      sessionsTable,
    } = await import("@workspace/db");
    const { taitoSessionDateTime } = await import("./session-schedule.ts");
    const { archiveExtraLiveSessionPrework } = await import("./session-prework-live.ts");

    const suffix = randomUUID();
    const [course] = await db
      .insert(coursesTable)
      .values({
        title: `English archive extras ${suffix}`,
        subject: "SAT & IELTS",
        term: "Fall 2026",
        status: "active",
      })
      .returning();
    const [session] = await db
      .insert(sessionsTable)
      .values({
        courseId: course!.id,
        dateTime: taitoSessionDateTime("2026-11-13"),
        timezone: "Asia/Tokyo",
        subject: "IELTS",
        title: "Taito’s English Session with Nika",
        status: "published",
        hasHomework: true,
      })
      .returning();
    const [olderComplete, emptyExtra] = await db
      .insert(assignmentsTable)
      .values([
        {
          courseId: course!.id,
          sessionId: session!.id,
          deliveryPhase: "before_session",
          title: "IELTS-style reading pre-work — Taito’s English Session with Nika",
          subject: "IELTS",
          instructions: "Complete copy.",
          status: "published",
          timeLimitMinutes: 21,
          maxAttempts: 1,
        },
        {
          courseId: course!.id,
          sessionId: session!.id,
          deliveryPhase: "before_session",
          title: "IELTS-style reading pre-work — Taito’s English Session with Nika",
          subject: "IELTS",
          instructions: "Empty extra.",
          status: "published",
          timeLimitMinutes: 21,
          maxAttempts: 1,
        },
      ])
      .returning();
    const [question] = await db
      .insert(questionsTable)
      .values({
        subject: "IELTS Reading",
        domain: "Reading",
        skill: "Matching",
        questionType: "multiple_choice",
        difficulty: "medium",
        prompt: `Archive keeper prompt ${suffix}`,
        choices: [{ id: "a", label: "A", text: "yes" }],
        correctAnswer: "a",
        explanation: "Because.",
        reviewStatus: "approved",
      })
      .returning({ id: questionsTable.id });
    await db.insert(assignmentQuestionsTable).values({
      assignmentId: olderComplete!.id,
      questionId: question!.id,
      position: 0,
    });
    await db.insert(sessionPreworkPlansTable).values({
      sessionId: session!.id,
      assignmentId: emptyExtra!.id,
      homeworkKind: "routine",
      targetMinutes: 21,
      estimatedSeconds: 1260,
      status: "assigned",
    });

    try {
      const result = await archiveExtraLiveSessionPrework({ courseId: course!.id });
      assert.equal(result.archivedAssignments, 1);
      const [kept] = await db
        .select()
        .from(assignmentsTable)
        .where(eq(assignmentsTable.id, olderComplete!.id));
      const [archived] = await db
        .select()
        .from(assignmentsTable)
        .where(eq(assignmentsTable.id, emptyExtra!.id));
      assert.equal(kept?.status, "published");
      assert.equal(archived?.status, "archived");
      const [plan] = await db
        .select()
        .from(sessionPreworkPlansTable)
        .where(eq(sessionPreworkPlansTable.sessionId, session!.id));
      assert.equal(plan?.assignmentId, olderComplete!.id);
    } finally {
      await db
        .delete(sessionPreworkPlansTable)
        .where(eq(sessionPreworkPlansTable.sessionId, session!.id));
      await db
        .delete(assignmentQuestionsTable)
        .where(inArray(assignmentQuestionsTable.assignmentId, [olderComplete!.id, emptyExtra!.id]));
      await db
        .delete(assignmentsTable)
        .where(inArray(assignmentsTable.id, [olderComplete!.id, emptyExtra!.id]));
      if (question?.id) {
        await db.delete(questionsTable).where(eq(questionsTable.id, question.id));
      }
      await db.delete(sessionsTable).where(eq(sessionsTable.id, session!.id));
      await db.delete(coursesTable).where(eq(coursesTable.id, course!.id));
    }
  },
);
