import { useState } from "react";
import {
  customFetch,
  useCloneAdminAssignmentToSession,
  useUpdateAdminAssignment,
  type AdminAssignment,
  type AdminSession,
  type AssignmentDetail,
} from "@workspace/api-client-react";
import { Library } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { quizRepositoryItems, quizRepositoryLabel } from "@/lib/quiz-repository";
import { sessionPreworkQuizzes } from "@/lib/assignable-bank-quizzes";
import { displaySessionTitle } from "@/lib/session-display";

function errorText(error: unknown): string {
  const data = (error as { data?: { error?: string } } | null)?.data;
  return data?.error || (error instanceof Error ? error.message : "The quiz could not be updated.");
}

export function TutorQuizRepository({
  quizzes,
  sessions,
  onChanged,
  onMessage,
}: {
  quizzes: AdminAssignment[];
  sessions: AdminSession[];
  onChanged: () => void;
  onMessage: (text: string) => void;
}) {
  const cloneAssignment = useCloneAdminAssignmentToSession();
  const updateAssignment = useUpdateAdminAssignment();
  const items = quizRepositoryItems(quizzes);
  const [previewId, setPreviewId] = useState<string | null>(null);
  const [preview, setPreview] = useState<AssignmentDetail | null>(null);
  const [assignQuizId, setAssignQuizId] = useState("");
  const [assignSessionId, setAssignSessionId] = useState("");
  const [swapSessionId, setSwapSessionId] = useState("");
  const [swapQuizId, setSwapQuizId] = useState("");

  const openPreview = async (assignmentId: string) => {
    setPreviewId(assignmentId);
    try {
      const detail = await customFetch<AssignmentDetail>(`/api/assignments/${assignmentId}`);
      setPreview(detail);
    } catch (error) {
      onMessage(errorText(error));
      setPreview(null);
    }
  };

  const assignDuplicate = () => {
    if (!assignQuizId || !assignSessionId) return;
    cloneAssignment.mutate(
      { assignmentId: assignQuizId, data: { sessionId: assignSessionId } },
      {
        onSuccess: () => {
          onMessage("Assigned a session-local duplicate. Edits there will not change this repository quiz.");
          onChanged();
        },
        onError: (error) => onMessage(errorText(error)),
      },
    );
  };

  const removeFromSession = (assignmentId: string) => {
    updateAssignment.mutate(
      { assignmentId, data: { status: "archived" } },
      {
        onSuccess: () => {
          onMessage("Removed the session quiz copy. The repository original is unchanged.");
          onChanged();
        },
        onError: (error) => onMessage(errorText(error)),
      },
    );
  };

  const swapOnSession = () => {
    if (!swapSessionId || !swapQuizId) return;
    const session = sessions.find((item) => item.id === swapSessionId);
    if (!session) return;
    const existing = sessionPreworkQuizzes(quizzes, session);
    const archiveNext = (index: number) => {
      const current = existing[index];
      if (!current) {
        cloneAssignment.mutate(
          { assignmentId: swapQuizId, data: { sessionId: swapSessionId, allowDuplicate: true } },
          {
            onSuccess: () => {
              onMessage("Swapped the session quiz for a fresh duplicate.");
              onChanged();
            },
            onError: (error) => onMessage(errorText(error)),
          },
        );
        return;
      }
      updateAssignment.mutate(
        { assignmentId: current.id, data: { status: "archived" } },
        {
          onSuccess: () => archiveNext(index + 1),
          onError: (error) => onMessage(errorText(error)),
        },
      );
    };
    archiveNext(0);
  };

  return (
    <details className="rounded-2xl border bg-card p-4" data-testid="tutor-quiz-repository">
      <summary className="flex cursor-pointer list-none items-center justify-between gap-3 font-semibold">
        <span className="flex items-center gap-2">
          <Library className="h-4 w-4 text-primary" />
          Quiz repository
        </span>
        <Badge variant="outline">{items.length} quizzes</Badge>
      </summary>
      <p className="mt-3 text-sm text-muted-foreground">
        Autogenerated booking quizzes and tutor-built bank quizzes. Assigning creates a session
        duplicate so later edits stay local.
      </p>
      <div className="mt-4 space-y-3">
        {items.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            Saved reusable quizzes and autogenerated SAT pre-work will appear here.
          </p>
        ) : (
          items.map((quiz) => (
            <div
              key={quiz.id}
              className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3"
              data-testid={`tutor-quiz-repo-item-${quiz.id}`}
            >
              <div>
                <p className="text-sm font-medium">{quizRepositoryLabel(quiz)}</p>
                {quiz.sessionId ? (
                  <p className="text-xs text-muted-foreground">Session copy · can be removed from that meeting</p>
                ) : (
                  <p className="text-xs text-muted-foreground">Reusable original · assign a duplicate to a session</p>
                )}
              </div>
              <div className="flex flex-wrap gap-2">
                <Button size="sm" variant="outline" onClick={() => void openPreview(quiz.id)}>
                  Preview
                </Button>
                {quiz.sessionId ? (
                  <Button size="sm" variant="ghost" onClick={() => removeFromSession(quiz.id)}>
                    Remove from session
                  </Button>
                ) : null}
              </div>
            </div>
          ))
        )}
      </div>

      <div className="mt-5 grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end">
        <div className="space-y-2">
          <Label htmlFor="tutor-repo-assign-quiz">Repository quiz</Label>
          <select
            id="tutor-repo-assign-quiz"
            data-testid="tutor-repo-assign-quiz"
            className="h-10 w-full rounded-md border bg-background px-3 text-sm"
            value={assignQuizId}
            onChange={(event) => setAssignQuizId(event.target.value)}
          >
            <option value="">Select a quiz</option>
            {items.map((quiz) => (
              <option key={quiz.id} value={quiz.id}>
                {quizRepositoryLabel(quiz)}
              </option>
            ))}
          </select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="tutor-repo-assign-session">Assign duplicate to</Label>
          <select
            id="tutor-repo-assign-session"
            data-testid="tutor-repo-assign-session"
            className="h-10 w-full rounded-md border bg-background px-3 text-sm"
            value={assignSessionId}
            onChange={(event) => setAssignSessionId(event.target.value)}
          >
            <option value="">Select a session</option>
            {sessions.map((session) => (
              <option key={session.id} value={session.id}>
                {displaySessionTitle(session.title, session.subject)}
              </option>
            ))}
          </select>
        </div>
        <Button
          data-testid="tutor-repo-assign-submit"
          disabled={cloneAssignment.isPending || !assignQuizId || !assignSessionId}
          onClick={assignDuplicate}
        >
          Assign a duplicate
        </Button>
      </div>

      <div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto] md:items-end">
        <div className="space-y-2">
          <Label htmlFor="tutor-repo-swap-session">Replace session quiz</Label>
          <select
            id="tutor-repo-swap-session"
            data-testid="tutor-repo-swap-session"
            className="h-10 w-full rounded-md border bg-background px-3 text-sm"
            value={swapSessionId}
            onChange={(event) => setSwapSessionId(event.target.value)}
          >
            <option value="">Select a session</option>
            {sessions.map((session) => (
              <option key={session.id} value={session.id}>
                {displaySessionTitle(session.title, session.subject)}
              </option>
            ))}
          </select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="tutor-repo-swap-quiz">With repository quiz</Label>
          <select
            id="tutor-repo-swap-quiz"
            data-testid="tutor-repo-swap-quiz"
            className="h-10 w-full rounded-md border bg-background px-3 text-sm"
            value={swapQuizId}
            onChange={(event) => setSwapQuizId(event.target.value)}
          >
            <option value="">Select a quiz</option>
            {items.map((quiz) => (
              <option key={quiz.id} value={quiz.id}>
                {quizRepositoryLabel(quiz)}
              </option>
            ))}
          </select>
        </div>
        <Button
          data-testid="tutor-repo-swap-submit"
          disabled={updateAssignment.isPending || cloneAssignment.isPending || !swapSessionId || !swapQuizId}
          onClick={swapOnSession}
        >
          Swap quiz
        </Button>
      </div>

      <Dialog
        open={Boolean(previewId)}
        onOpenChange={(open) => {
          if (!open) {
            setPreviewId(null);
            setPreview(null);
          }
        }}
      >
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{preview?.title ?? "Quiz preview"}</DialogTitle>
            <DialogDescription>
              Correct answers and explanations are visible to tutors. Students still see MCQ stems only.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3">
            {(preview?.questions ?? []).map((question, index) => (
              <div key={question.id} className="rounded-lg border p-3 text-sm">
                <p className="font-medium">
                  {index + 1}. {question.prompt}
                </p>
                <ul className="mt-2 space-y-1 text-muted-foreground">
                  {(question.choices ?? []).map((choice) => (
                    <li key={choice.id}>
                      {choice.label}. {choice.text}
                      {question.correctAnswer === choice.id ? " · correct" : ""}
                    </li>
                  ))}
                </ul>
                {question.explanation ? (
                  <p className="mt-2 text-xs text-muted-foreground">{question.explanation}</p>
                ) : null}
              </div>
            ))}
          </div>
        </DialogContent>
      </Dialog>
    </details>
  );
}
